FROM alpine

LABEL key="amoussai"

RUN apk update && \
    apk add influxdb && \
    apk add openrc && \
    openrc default && \
    rc-service influxdb restart && \
    sleep 3 && \
    influx -execute "CREATE USER \"admin\" WITH PASSWORD 'password' WITH ALL PRIVILEGES" && \
    influx -username admin -password password -execute "CREATE DATABASE ft_services"
 
COPY ./srcs/startup.sh /bin/

RUN chmod 755 /bin/startup.sh

EXPOSE 8086

CMD ["startup.sh"]

