FROM alpine

LABEL key="amoussai"

RUN apk update && \
    apk add influxdb && \
    apk add openrc && \
    openrc default && \
    rc-service influxdb restart && \
    sleep 3 && \
    influx -execute "CREATE USER \"admin\" WITH PASSWORD 'password' WITH ALL PRIVILEGES" && \
    apk add telegraf --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
 
COPY ./srcs/startup.sh /bin/
COPY ./srcs/telegraf.conf ./etc/

RUN chmod 755 /bin/startup.sh

EXPOSE 8086

CMD ["startup.sh"]

