apiVersion: apps/v1 
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        imagePullPolicy: Never
        image: grafana:mine
        livenessProbe:
          exec:
            command:
            - pgrep
            - grafana
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: 200Mi
            cpu: "100m"
        ports:
        -   name: grafana
            containerPort: 3000
            hostPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: grafana
    labels:
        tier: grafana
spec:
    type: LoadBalancer
    selector:
        app: ft_services
        tier: grafana
    ports:
        -   targetPort: 3000
            port: 3000
            name: grafana