apiVersion: apps/v1 
kind: Deployment
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        imagePullPolicy: Never
        image: influxdb:mine
        livenessProbe:
          exec:
            command:
            - pgrep
            - influxd
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: 200Mi
            cpu: "100m"
        ports:
        -   name: influxdb
            containerPort: 8086
            hostPort: 8086
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: influxdb
    labels:
        tier: influxdb
spec:
    type: ClusterIP
    selector:
        app: ft_services
        tier: influxdb
    ports:
        -   targetPort: 8086
            port: 8086
            name: influxdb