apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        imagePullPolicy: Never
        image: mysql:mine
        livenessProbe:
          exec:
            command:
            - pgrep
            - mysqld
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: 200Mi
            cpu: "100m"
        ports:
        -   name: mysql
            containerPort: 3306
            hostPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvcx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvcx
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: mysql
    labels:
        tier: mysql
spec:
    type: ClusterIP
    selector:
        app: ft_services
        tier: mysql
    ports:
        -   targetPort: 3306
            port: 3306
            name: mysql
