apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        imagePullPolicy: Never
        image: nginx:mine
        resources:
          limits:
            memory: 200Mi
            cpu: "100m"
        ports:
        -   name: nginx
            containerPort: 80
            hostPort: 80
        -   name: nginx-ssl
            containerPort: 443
            hostPort: 443
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
    labels:
        tier: nginx
spec:
    type: LoadBalancer
    selector:
        app: ft_services
        tier: nginx
    ports:
        -   targetPort: 80
            port: 80
            name: nginx
        -   targetPort: 443
            port: 443
            name: nginx-ssl