apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        imagePullPolicy: Never
        image: nginx:mine
        livenessProbe:
          exec:
            command:
            - sh
            - /verif.sh
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          limits:
            memory: 200Mi
            cpu: "100m"
        ports:
        -   name: nginx
            containerPort: 80
            hostPort: 80
        -   name: nginx-ssl
            containerPort: 443
            hostPort: 443
        -   name: nginx-ssh
            containerPort: 600
            hostPort: 600
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: nginx
    labels:
        tier: nginx
spec:
    type: LoadBalancer
    selector:
        app: ft_services
        tier: nginx
    ports:
        -   targetPort: 80
            port: 80
            name: nginx
        -   targetPort: 443
            port: 443
            name: nginx-ssl
        -   targetPort: 600
            port: 600
            name: nginx-ssh
