apiVersion: apps/v1 
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        imagePullPolicy: Never
        image: phpmyadmin:mine
        livenessProbe:
          exec:
            command:
            - sh
            - /verif.sh
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          limits:
            memory: 200Mi
            cpu: "100m"
        ports:
        -   name: phpmyadmin
            containerPort: 5000
            hostPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: phpmyadmin
    labels:
        tier: phpmyadmin
spec:
    type: LoadBalancer
    selector:
        app: ft_services
        tier: phpmyadmin
    ports:
        -   targetPort: 5000
            port: 5000
            name: phpmyadmin
