apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        imagePullPolicy: Never
        image: wordpress:mine
        livenessProbe:
          exec:
            command:
            - sh
            - /verif.sh
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          limits:
            memory: 200Mi
            cpu: "100m"
        ports:
        -   name: wordpress
            containerPort: 5050
            hostPort: 5050
---
apiVersion: v1
kind: Service
metadata:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
    name: wordpress
    labels:
        tier: wordpress
spec:
    type: LoadBalancer
    selector:
        app: ft_services
        tier: wordpress
    ports:
        -   targetPort: 5050
            port: 5050
            name: wordpress
