FROM alpine

LABEL key="amoussai"

RUN apk update && \
    apk add openrc && \
    apk add mysql mysql-client

COPY ./srcs/my.cnf /
COPY ./srcs/phpmyadmin.sql /

    
RUN mkdir /run/openrc && \
    touch /run/openrc/softlevel && \
    mkdir /app && \
    mkdir /app/mysql && \
    echo "hello there **********************************"
    

COPY ./srcs/startup.sh /bin/

RUN chmod 755 /bin/startup.sh

EXPOSE 3306

CMD ["startup.sh"]


