FROM alpine

LABEL key="amoussai"

RUN apk update && \
    apk add openrc && \
    apk add vim && \
    wget https://dl.grafana.com/oss/release/grafana-7.3.1.linux-amd64.tar.gz && \
    tar -zxvf grafana-7.3.1.linux-amd64.tar.gz && \
    mv grafana-7.3.1 grafana && \
    apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main libc6-compat && \
    cp /grafana/conf/sample.ini /grafana/conf/custom.ini

COPY ./srcs/datasource.yaml /grafana/conf/provisioning/datasources/
COPY ./srcs/startup.sh /bin/

RUN chmod 755 /bin/startup.sh

EXPOSE 3000

CMD ["startup.sh"]

