FROM alpine:latest
LABEL maintainer="amoussai"

ENV SERVERNAME 192.168.99.101

ENV COUNTRY MA
ENV STATE Khouribga
ENV LOCALITY Khouribga
ENV ORGANIZATION 1337FIL

RUN apk update ; \
	apk upgrade ; \
	apk add nginx ; \
	apk add openrc ; \
	apk add php-fpm ; \
	apk add php-curl ; \
	apk add php-gd ; \
	apk add php-intl ; \
	apk add php-mbstring ; \
	apk add php-soap ; \
	apk add php-xml ; \
	apk add php-xmlrpc ; \
	apk add php-zip ; \
	apk add php-pear ; \
	apk add php-gettext ; \
	apk add php-cgi ; \
	apk add vim ; \
	apk add openssh ; \
	apk add telegraf --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing



ADD ./srcs/script.sh /usr/bin/script.sh
ADD ./srcs/listener.sh /usr/bin/listener.sh 
RUN mkdir -p /run/nginx && mkdir /www

RUN openrc default && rc-update add sshd && /etc/init.d/sshd start

COPY ./srcs/index.html /www
COPY ./srcs/default.conf /etc/nginx/conf.d/
COPY ./srcs/sshd_config /etc/ssh/
COPY /srcs/verif.sh /
COPY ./srcs/telegraf.conf ./etc/

RUN chmod 755 /usr/bin/script.sh && \
	chmod 755 /usr/bin/listener.sh && \
	adduser sshuser -D && \
    echo "sshuser:password" | chpasswd && \
	chmod 777 verif.sh


RUN sh /usr/bin/script.sh


EXPOSE 80 443 600

ENTRYPOINT ["sh", "/usr/bin/listener.sh"]
