FROM alpine

LABEL key="amoussai"

RUN apk update && \
    apk add nginx && \
    apk add openrc && \
    apk add vim && \
    openrc default && \
    adduser -D -g 'www' www && \
    mkdir /var/www/test && \
    chown -R www:www /var/lib/nginx && \
    chown -R www:www /var/www/test && \
    mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig && \
    apk add php-session php-mbstring php7-common php7-iconv php7-json php7-gd php7-curl php7-zlib php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom && \
    apk add php-mysqli && \
    apk add php7 php7-fpm php7-opcache && \ 
    wget http://wordpress.org/latest.tar.gz -P /var/www/test && \
    tar -xzvf /var/www/test/latest.tar.gz -C /var/www/test && \
    rm /var/www/test/latest.tar.gz && \
    chmod -R 777 /var/www/test && \
    chmod -R 777 /var/www/test/wordpress && \
    ln -s /var/www/test/wordpress /var/www/localhost/htdocs/wordpress && \
    rc-update add nginx default && \
    rc-update add php-fpm7 default

COPY ./srcs/nginx.conf /etc/nginx/
COPY ./srcs/wp-config.php /var/www/test/wordpress/wp-config.php
COPY ./srcs/wp-config2.php /

RUN wget https://api.wordpress.org/secret-key/1.1/salt/ && \
    cat /index.htm* >> /var/www/test/wordpress/wp-config.php && \
    cat /wp-config2.php >> /var/www/test/wordpress/wp-config.php && \
    apk add telegraf --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing

COPY ./srcs/startup.sh /bin/
COPY /srcs/verif.sh /
COPY ./srcs/telegraf.conf ./etc/

RUN chmod 755 /bin/startup.sh && \
    chmod 777 /verif.sh

EXPOSE 5050

CMD ["startup.sh"]
