FROM alpine

LABEL key="amoussai"

RUN apk update && \
    apk add openrc && \
    apk add vim && \
    apk add telegraf --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing

COPY ./srcs/startup.sh /bin/

RUN chmod 755 /bin/startup.sh

CMD ["startup.sh"]

